### ISSUE TITLE
support for OLED switch

### ISSUE THREAD

**Issue by ZweiBR** [TTghostsemir/fastCFWswitch#3]
wanted to know if it works in version 16.0.3?

**Comment by TTghostsemir** [comment]
It should work on Firmware 16.0.3

**Comment by EnricoSanchez** [comment]
> wanted to know if it works in version 16.0.3?

Yes it works for me

**Comment by ZweiBR** [comment]
I will test, thanks

**Comment by ZweiBR** [comment]
> > wanted to know if it works in version 16.0.3?
> 
> Yes it works for me

https://a.imagem.app/beACDQ.jpg

How do I make the options appear?

**Comment by HeikesFootSlave** [comment]
What do you mean with options?

You can set fastCFWswitch up with it's config in SD:/config/fastCFWSwitch/config.ini

**Comment by ZweiBR** [comment]
> What do you mean with options?
> 
> You can set fastCFWswitch up with it's config in SD:/config/fastCFWSwitch/config.ini

for example
I want to enter directly into the hekate option

**Comment by HeikesFootSlave** [comment]
And the readme on main page how to configure doesn't help 🤔

[HEKATE]
name=hekate
path=/bootloader/update.bin

**Comment by ZweiBR** [comment]
> 

About the configuration I understood how to do it.
I want to know the following, how do I reboot the main screen
